### ISSUE TITLE
Please bump to 1.8.26

### ISSUE THREAD

**Issue by rabievdm** [iuscommunity-pkg/haproxy18u#14]
New upstream update with multiple fixes, please bump the build up to 1.8.26
http://www.haproxy.org/download/1.8/src/CHANGELOG

**Comment by carlwgeorge** [comment]
haproxy18u-1.8.26-1.el7.ius is now available in the testing repository.  It will be promoted to the main repository after one week, or sooner with testing feedback here.

**Comment by carlwgeorge** [comment]
haproxy18u-1.8.26-1.el7.ius was released to the main repo already, just forgot to close this out.
