### ISSUE TITLE
Please upgrade to 1.8.27

### ISSUE THREAD

**Issue by yoyonl** [iuscommunity-pkg/haproxy18u#15]
Hi,

As Haproxy released version 1.8.27 on 2020/11/06, is it possible that IUS also get this update?
We have a bug that in 1.8.26 that is fixed 1.8.27. 

http://git.haproxy.org/?p=haproxy-1.8.git;a=blob_plain;f=CHANGELOG

Thanks

**Comment by carlwgeorge** [comment]
haproxy18u-1.8.28-1.el7.ius has been published to the testing repo.

**Comment by yoyonl** [comment]
Thanks Carl, when will haproxy18u-1.8.28-1.el7.iu pushed to production?

**Comment by carlwgeorge** [comment]
I've pushed haproxy18u-1.8.28-1.el7.ius to the main repo.
