### ISSUE TITLE
Update to 1.8.4

### ISSUE THREAD

**Issue by kustodian** [iuscommunity-pkg/haproxy18u#4]
HAProxy 1.8.4 has been released a few days ago and it fixes a lot of bugs [changelog](http://www.haproxy.org/download/1.8/src/CHANGELOG).

**Comment by b-harper** [comment]
Hey @kustodian,

We have already built haproxy18u-1.8.4-1 packages and they are currently in the [testing repository][0]. 


[0]: https://github.com/iuscommunity-pkg/haproxy18u/releases/tag/1.8.4-1
