### ISSUE TITLE
Update haproxy to version 1.8.6

### ISSUE THREAD

**Issue by dseira** [iuscommunity-pkg/haproxy18u#6]
The version that is in the IUS repo is 1.8.4 which has several bugs related to the HTTP/2 support that produce a random segfault. Are there any plans to upgrade the haproxy package to version 1.8.6?

Thanks,
David

**Comment by carlwgeorge** [comment]
Even better, we plan on updating it to version 1.8.7!  If you watch this GitHub repo you should get a notification when I tag the release.  I don't have an ETA on completing it but feedback like this helps me to prioritize things, so thank you.

**Comment by dseira** [comment]
Thank you very much! We are really expecting it!

**Comment by carlwgeorge** [comment]
[haproxy-1.8.7-1](https://github.com/iuscommunity-pkg/haproxy18u/releases/tag/1.8.7-1) is done and will hit the testing repos during tonight's automation.

**Comment by dseira** [comment]
Thanks! I will test the pkg when it is available in the repo.
