### ISSUE TITLE
cannot read stats socket unless root

### ISSUE THREAD

**Issue by packeteer** [iuscommunity-pkg/haproxy18u#8]
error:
`haproxy_exporter[2911]: time="2018-10-09T10:52:09+11:00" level=error msg="Can't scrape HAProxy: dial unix /var/lib/haproxy/stats: connect: permission denied" source="haproxy_exporter.go:315"`

As above, I'm trying to get the Prometheus haproxy_exporter to send haproxy stats to Prometheus. Unfortunately the haproxy service is not setting the correct group permissions on the stats file

config excerpt:

global
log         127.0.0.1 local2
chroot      /var/lib/haproxy
pidfile     /run/haproxy.pid
maxconn     2048
user        haproxy
group       haproxy
daemon
stats socket /run/haproxy/stats mode 640

stats socket:
`srw-r-----.  1 root root      0 Oct  9 14:35 stats`

Does anyone have a suggestion on how to solve this?

**Comment by carlwgeorge** [comment]
From what I'm reading in the manual it seems that you have to pass the `user` and `group` parameters to the `stats socket` directive.

* https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#3.1-stats%20socket
* https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.1-user
* https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.1-group

The `user` and `group` in the `global` config section refer to the worker processes.  The master process is running as root:root, so I'm assuming that is what the stats socket defaults to.  Can you try setting the `user` and `group` parameters for `stats socket` and see if it works?

**Comment by packeteer** [comment]
Thanks for that, it took a few tries but the following config sets the correct permissions:
`stats socket /run/haproxy/stats mode 640 group haproxy`

Unfortunately the prometheus exporter still fails with a permissions error:
`Oct 10 17:16:23 haproxy01 haproxy_exporter: time="2018-10-10T17:16:23+11:00" level=error msg="Can't scrape HAProxy: dial unix /run/haproxy/admin.sock: connect: permission denied" source="haproxy_exporter.go:315"`

fwiw, the previous config works fine on Ubuntu 16.04 LTS with haproxy 1.8.12 ?!?
I thought it might be selinux related, but that is in permissive mode

Anyway, I'll take it up with the Prometheus people. Thanks!

**Comment by marji** [comment]
@packeteer Just in case you haven't noticed - I can see in your previous comment that your socket path is defined as `/run/haproxy/stats` while haproxy_exporter is trying to read from `/run/haproxy/admin.sock`

**Comment by packeteer** [comment]
@marji thanks, I was experimenting with different paths and posted non matching config + error. Unfortunately the error persists, so I've shelved it for now.
