### ISSUE TITLE
Update to 1.9.1

### ISSUE THREAD

**Issue by thehaven** [iuscommunity-pkg/haproxy18u#9]
This likely needs its own repo for the minor revision bump, but raising it in here anyway. Now that 1.9.1 is out please can we get a build for it in IUS?

I've a build example, which is just a copy of the haproxy18u code, at the repo below if you are interested. I'm still testing it but so far nothing has jumped out and surprised me:

https://github.com/thehaven/haproxy19u

Many thanks

**Comment by carlwgeorge** [comment]
You're right, it will be a new package. Please open a request for haproxy19 on the [wishlist](https://github.com/iuscommunity/wishlist).

**Comment by thehaven** [comment]
Thanks, done:

https://github.com/iuscommunity/wishlist/issues/224
